pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' 

- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'IOSapplication/IOSazureartifact'
    vstsFeedPackagePublish: 'publish'
    versionOption: custom
    versionPublish: '1.0.1'

- task: UniversalPackages@0
  displayName: 'Universal download'
  inputs:
    command: download
    vstsFeed: 'IOSapplication/IOSazureartifact'
    vstsFeedPackage: 'publish'
    vstsPackageVersion: '1.0.1'
    downloadDirectory: '$(Build.SourcesDirectory)\someFolder'
    